# Generated by Django 6.0.3 on 2026-03-14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_newslettersubscriber_contactmessage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "-created_at"],
                name="post_status_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title",
                    config="english",
                    weight="A",
                )
                + django.contrib.postgres.search.SearchVector(
                    "excerpt",
                    config="english",
                    weight="B",
                )
                + django.contrib.postgres.search.SearchVector(
                    "content",
                    config="english",
                    weight="C",
                ),
                name="post_search_vector_gin",
            ),
        ),
    ]
