# Generated by Django 6.0.3 on 2026-03-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_suggestion_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_date", models.DateField()),
                ("visitor_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_views",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="postview",
            constraint=models.UniqueConstraint(
                fields=("post", "view_date", "visitor_hash"),
                name="unique_daily_post_view",
            ),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(fields=["post", "view_date"], name="postview_post_date_idx"),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(fields=["view_date"], name="postview_date_idx"),
        ),
        migrations.AddIndex(
            model_name="postview",
            index=models.Index(fields=["visitor_hash"], name="postview_hash_idx"),
        ),
    ]
