# Generated by Django 6.0.3 on 2026-03-14

import re
from html import unescape

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


def backfill_search_headings(apps, schema_editor):
    post_model = apps.get_model("blog", "Post")

    heading_pattern = re.compile(
        r"<h[1-6][^>]*>(.*?)</h[1-6]>",
        flags=re.IGNORECASE | re.DOTALL,
    )
    tag_pattern = re.compile(r"<[^>]+>")

    for post in post_model.objects.all().only("id", "content"):
        heading_matches = heading_pattern.findall(str(post.content or ""))
        cleaned_headings = []
        for raw_heading in heading_matches:
            without_tags = tag_pattern.sub(" ", raw_heading)
            normalized = re.sub(r"\s+", " ", unescape(without_tags)).strip()
            if normalized:
                cleaned_headings.append(normalized)

        post.search_headings = " ".join(cleaned_headings)[:4000]
        post.save(update_fields=["search_headings"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_postview_and_views_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="search_headings",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(backfill_search_headings, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="post",
            name="post_search_vector_gin",
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "title",
                    config="english",
                    weight="A",
                )
                + django.contrib.postgres.search.SearchVector(
                    "search_headings",
                    config="english",
                    weight="B",
                )
                + django.contrib.postgres.search.SearchVector(
                    "content",
                    config="english",
                    weight="C",
                ),
                name="post_search_vector_gin",
            ),
        ),
    ]
