# Generated by Django 6.0.3 on 2026-03-18 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_faq_blocks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PUBLISH', 'Publish'), ('SEARCH', 'Search'), ('SCROLL_DEPTH', 'Scroll Depth')], max_length=30)),
                ('query', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='', max_length=60)),
                ('visitor_hash', models.CharField(blank=True, default='', max_length=64)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('depth_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialAutosave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_key', models.CharField(default='new-post', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('publish_post', 'Can schedule publication for posts')]},
        ),
        migrations.AddField(
            model_name='post',
            name='ad_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='disclosure_text',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='post',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='premium_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='post_status_publish_idx'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='blog.post'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialautosave',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_autosaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialautosave',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autosaves', to='blog.post'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', '-created_at'], name='analytic_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['query'], name='analytic_query_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['post', 'event_type'], name='analytic_post_type_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialautosave',
            index=models.Index(fields=['author', '-updated_at'], name='autosave_author_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialautosave',
            index=models.Index(fields=['draft_key'], name='autosave_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='editorialautosave',
            constraint=models.UniqueConstraint(fields=('author', 'draft_key'), name='unique_editorial_autosave_per_author_key'),
        ),
    ]
